import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const exports = ['DataError', 'parseCSV', 'validateTable', 'serializeCSV', 'tableToObjects', 'parseJSONTable', 'cleanTable', 'duplicateIndexes'];
export function browserBundle(source) {
  return `/* Generated from csv.mjs by node build.mjs. Do not edit this file. */\n(() => {\n'use strict';\n${source.replace(/^export /gm, '')}\nglobalThis.ClearTabData = Object.freeze({ ${exports.join(', ')} });\n})();\n`;
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await writeFile(new URL('csv-browser.js', import.meta.url), browserBundle(await readFile(new URL('csv.mjs', import.meta.url), 'utf8')));
  console.log('Built csv-browser.js for offline file:// use.');
}
